services:
  django-api:
    build: .
    image: catapiicmc/django-cat-api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - cat-api

networks:
  cat-api:
    external: true
    name: cat-api