# Generated by Django 4.2.11 on 2025-02-23 18:25

import core.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('finished', 'Finalizado'), ('error', 'Erro')], default='processing', max_length=10)),
                ('type', models.CharField(choices=[('create_users', 'Criar Usuários em Massa')], max_length=50)),
                ('file', models.FileField(upload_to='upload')),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processo em Massa',
                'verbose_name_plural': 'Processos em Massa',
                'db_table': 'mass_process',
            },
        ),
    ]
