# Generated by Django 4.2.11 on 2024-11-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_questionsuperpool_questionpool_super_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='criteria',
            field=models.CharField(choices=[('seq', 'Sequencial'), ('random', 'Aleatório'), ('MI', 'MI - Máxima Informação'), ('MEPV', 'MEPV - Mínima Variância Posterior Esperada'), ('MLWI', 'MLWI - Informação Ponderada de Máxima Verossimilhança'), ('MPWI', 'MPWI - Informação Ponderada Máxima Posterior'), ('MEI', 'MEI - Informação Esperada Máxima'), ('KL', 'KL - Divergência Kullback-Leibler ponto a ponto'), ('KLn', 'KLn - Kullback-Leibler ponto a ponto com um valor delta decrescente'), ('IKLP', 'IKLP - Critérios de Kullback-Leibler Baseados em Integração com peso de densidade a priori'), ('IKL', 'IKL - Critérios de Kullback-Leibler Baseados em Integração'), ('IKLn', 'IKLn - Versão ponderada com itens raiz-n'), ('IKLPn', 'IKLPn - Versão ponderada com itens raiz-n'), ('Drule', 'DRULE - Determinante Máximo da Matriz de Informação'), ('Trule', 'TRULE - Traço Máximo (potencialmente ponderado) da Matriz de Informação'), ('Arule', 'ARULE - Traço Mínimo (potencialmente ponderado) da Matriz de Covariância Assintótica'), ('Erule', 'ERULE - Valor Mínimo da Matriz de Informação'), ('Wrule', 'WRULE - Critérios de Informação Ponderada'), ('DPrule', 'DPRULE - Para Drule'), ('TPrule', 'TPRULE - Para Trule'), ('APrule', 'APRULE - Para Arule'), ('EPrule', 'EPRULE - Para Erule'), ('WPrule', 'WPRULE - Para Wrule')], default='seq', max_length=255, verbose_name='Critério de Seleção'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='delta_thetas',
            field=models.CharField(default='0', help_text="Valor de diferença entre thetas. Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional. O padrão '0' desabilita este critério de parada.", max_length=255, verbose_name='Delta Thetas'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_items',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de Itens'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_time',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Tempo máximo em segundos. Deixe em branco para ilimitado', null=True, verbose_name='Tempo Máximo'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='min_items',
            field=models.PositiveIntegerField(default=1, verbose_name='Mínimo de Itens'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='min_sem',
            field=models.CharField(default='0.3', help_text='Valor mínimo de erro padrão de medida. Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional.', max_length=255, verbose_name='Mínimo de SEM'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_item',
            field=models.PositiveIntegerField(default=1, verbose_name='Item Inicial'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='thetas_start',
            field=models.CharField(default='-3,3', help_text='Valor inicial de thetas. Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional.', max_length=255, verbose_name='Thetas Iniciais'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('3PL', 'TRI - 3 Parâmetros'), ('2PL', 'TRI - 2 Parâmetros'), ('1PL', 'TRI - 1 Parâmetro'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO')], default='3PL', max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='finish',
            field=models.DateTimeField(blank=True, default=None, help_text='Deixe em branco para não finalizar', null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start',
            field=models.DateTimeField(blank=True, default=None, help_text='Deixe em branco para iniciar imediatamente', null=True, verbose_name='Início'),
        ),
    ]
