# Generated by Django 4.2.11 on 2024-11-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_assessment_criteria_assessment_delta_thetas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='thetas_start',
            field=models.CharField(default='0', help_text='Valor inicial de thetas. Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional.', max_length=255, verbose_name='Thetas Iniciais'),
        ),
    ]
