# Generated by Django 4.2.11 on 2024-11-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_assessment_thetas_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='pattern_theta',
            field=models.CharField(default='0', help_text='Valor de theta inicial. Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional.', max_length=255, verbose_name='Padrão de Theta'),
        ),
    ]
