# Generated by Django 4.2.11 on 2025-01-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_assessment_pattern_theta'),
    ]

    operations = [
        migrations.AddField(
            model_name='mirtdesigndata',
            name='item_time_history',
            field=models.JSONField(default=list, verbose_name='Histórico de Tempo de Resposta'),
        ),
        migrations.AddField(
            model_name='mirtdesigndata',
            name='last_answer_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Última Resposta'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='start_item',
            field=models.PositiveIntegerField(default=1, help_text='Caso o índice seja 0, o primeiro item será escolhido aleatoriamente.', verbose_name='Item Inicial'),
        ),
    ]
