# Generated by Django 4.2.11 on 2025-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_mirtdesigndata_item_time_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='retry',
            field=models.BooleanField(default=False, help_text='Permite que o usuário repita a avaliação caso já tenha finalizado', verbose_name='Permitir Repetição'),
        ),
    ]
