# Generated by Django 4.2.11 on 2025-10-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_assessment_retry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='discrimination',
        ),
        migrations.RemoveField(
            model_name='question',
            name='guess',
        ),
    ]
