# Generated by Django 4.2.11 on 2025-10-05 18:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_remove_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('4PL', 'TRI - 4 Parâmetros'), ('3PL', 'TRI - 3 Parâmetros'), ('2PL', 'TRI - 2 Parâmetros'), ('1PL', 'TRI - 1 Parâmetro'), ('4PL', 'TRI - 4 Parâmetros Multidimensionais'), ('3PL', 'TRI - 3 Parâmetros Multidimensionais'), ('2PL', 'TRI - 2 Parâmetros Multidimensionais'), ('1PL', 'TRI - 1 Parâmetro Multidimensional'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - GDINA')], default='3PL', max_length=255, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='QuestionParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irt_discrimination', models.FloatField(default=1.0, verbose_name='Discriminação')),
                ('irt_difficulty', models.FloatField(default=0.0, verbose_name='Dificuldade')),
                ('irt_guess', models.FloatField(default=0.0, verbose_name='Chute')),
                ('irt_upper_asymptote', models.FloatField(default=1.0, verbose_name='Assimptota Superior')),
                ('irt_mparams', models.JSONField(default=list, verbose_name='Parâmetros Multidimensionais')),
                ('cdm_slipping', models.FloatField(default=0.0, verbose_name='Deslize')),
                ('cdm_guessing', models.FloatField(default=0.0, verbose_name='Chute')),
                ('cdm_mparams', models.JSONField(default=list, verbose_name='Parâmetros Multidimensionais')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('model', models.CharField(choices=[('4PL', 'TRI - 4 Parâmetros'), ('3PL', 'TRI - 3 Parâmetros'), ('2PL', 'TRI - 2 Parâmetros'), ('1PL', 'TRI - 1 Parâmetro'), ('4PL', 'TRI - 4 Parâmetros Multidimensionais'), ('3PL', 'TRI - 3 Parâmetros Multidimensionais'), ('2PL', 'TRI - 2 Parâmetros Multidimensionais'), ('1PL', 'TRI - 1 Parâmetro Multidimensional'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - GDINA')], default='3PL', max_length=255, verbose_name='Modelo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='learning.question')),
            ],
            options={
                'db_table': 'question_params',
            },
        ),
    ]
