# Generated by Django 4.2.11 on 2025-10-05 18:56

import core.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_alter_assessment_type_questionparams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionparams',
            options={'verbose_name': 'Parâmetros de Questão', 'verbose_name_plural': 'Parâmetros de Questões'},
        ),
        migrations.AddField(
            model_name='questionparams',
            name='created',
            field=core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='questionparams',
            name='modified',
            field=core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='questionparams',
            name='removed',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
