# Generated by Django 4.2.11 on 2025-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_questionparams_options_questionparams_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionparams',
            name='cdm_qmatrix',
            field=models.JSONField(default=list, verbose_name='Valores para a Matriz Q'),
        ),
    ]
