# Generated by Django 4.2.11 on 2025-10-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_questionparams_cdm_qmatrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('4PL', 'TRI - 4 Parâmetros'), ('3PL', 'TRI - 3 Parâmetros'), ('2PL', 'TRI - 2 Parâmetros'), ('1PL', 'TRI - 1 Parâmetro'), ('M4PL', 'TRI - 4 Parâmetros Multidimensionais'), ('M3PL', 'TRI - 3 Parâmetros Multidimensionais'), ('M2PL', 'TRI - 2 Parâmetros Multidimensionais'), ('M1PL', 'TRI - 1 Parâmetro Multidimensional'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - GDINA')], default='3PL', max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='questionparams',
            name='model',
            field=models.CharField(choices=[('4PL', 'TRI - 4 Parâmetros'), ('3PL', 'TRI - 3 Parâmetros'), ('2PL', 'TRI - 2 Parâmetros'), ('1PL', 'TRI - 1 Parâmetro'), ('M4PL', 'TRI - 4 Parâmetros Multidimensionais'), ('M3PL', 'TRI - 3 Parâmetros Multidimensionais'), ('M2PL', 'TRI - 2 Parâmetros Multidimensionais'), ('M1PL', 'TRI - 1 Parâmetro Multidimensional'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - GDINA')], default='3PL', max_length=255, verbose_name='Modelo'),
        ),
    ]
