# Generated by Django 4.2.11 on 2025-10-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_alter_assessment_type_alter_questionparams_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionparams',
            unique_together={('model', 'question')},
        ),
    ]
