# Generated by Django 4.2.11 on 2025-11-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_alter_questionparams_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='method',
            field=models.CharField(choices=[('MAP', 'MAP - Máxima a Posteriori'), ('EAP', 'EAP - Esperança a Posteriori'), ('MLE', 'MLE - Máxima Verossimilhança')], default='MLE', max_length=255, verbose_name='Método de Estimação'),
        ),
    ]
