# Generated by Django 4.2.11 on 2026-02-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_assessment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='pattern_theta',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='criteria',
            field=models.CharField(choices=[('seq', 'Sequencial'), ('random', 'Aleatório'), ('MI', 'MI - Máxima Informação'), ('MEPV', 'MEPV - Mínima Variância Posterior Esperada'), ('MLWI', 'MLWI - Informação Ponderada de Máxima Verossimilhança'), ('MPWI', 'MPWI - Informação Ponderada Máxima Posterior'), ('MEI', 'MEI - Informação Esperada Máxima'), ('KL', 'KL - Divergência Kullback-Leibler ponto a ponto'), ('KLn', 'KLn - Kullback-Leibler ponto a ponto com um valor delta decrescente'), ('IKLP', 'IKLP - Critérios de Kullback-Leibler Baseados em Integração com peso de densidade a priori'), ('IKL', 'IKL - Critérios de Kullback-Leibler Baseados em Integração'), ('IKLn', 'IKLn - Versão ponderada com itens raiz-n'), ('IKLPn', 'IKLPn - Versão ponderada com itens raiz-n'), ('Drule', 'DRULE - Determinante Máximo da Matriz de Informação'), ('Trule', 'TRULE - Traço Máximo (potencialmente ponderado) da Matriz de Informação'), ('Arule', 'ARULE - Traço Mínimo (potencialmente ponderado) da Matriz de Covariância Assintótica'), ('Erule', 'ERULE - Valor Mínimo da Matriz de Informação'), ('Wrule', 'WRULE - Critérios de Informação Ponderada'), ('DPrule', 'DPRULE - Para Drule'), ('TPrule', 'TPRULE - Para Trule'), ('APrule', 'APRULE - Para Arule'), ('EPrule', 'EPRULE - Para Erule'), ('WPrule', 'WPRULE - Para Wrule'), ('SHE', 'SHE - Entropia Shennon da Habilidade do Sujeito'), ('CDMKL', 'KL - Divergência Kullback-Leibler'), ('PWKL', 'PWKL - Divergência Kullback-Leibler Ponderada'), ('MPWKL', 'MPWKL - Divergência Kullback-Leibler Ponderada de Máxima Posterior')], default='seq', max_length=255, verbose_name='Critério de Seleção de Itens'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='method',
            field=models.CharField(choices=[('MAP', 'MAP - Máxima a Posteriori'), ('EAP', 'EAP - Esperança a Posteriori'), ('MLE', 'MLE - Máxima Verossimilhança')], default='MLE', max_length=255, verbose_name='Método de Estimação de Proficiência'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('4PL', 'TRI - 4PL'), ('3PL', 'TRI - 3PL'), ('2PL', 'TRI - 2PL'), ('1PL', 'TRI - 1PL (Rasch)'), ('M4PL', 'TRI - M4PL'), ('M3PL', 'TRI - M3PL'), ('M2PL', 'TRI - M2PL'), ('M1PL', 'TRI - M1PL'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - G-DINA')], default='3PL', max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='questionparams',
            name='model',
            field=models.CharField(choices=[('4PL', 'TRI - 4PL'), ('3PL', 'TRI - 3PL'), ('2PL', 'TRI - 2PL'), ('1PL', 'TRI - 1PL (Rasch)'), ('M4PL', 'TRI - M4PL'), ('M3PL', 'TRI - M3PL'), ('M2PL', 'TRI - M2PL'), ('M1PL', 'TRI - M1PL'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - G-DINA')], default='3PL', max_length=255, verbose_name='Modelo'),
        ),
    ]
