# Generated by Django 4.2.11 on 2026-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_remove_assessment_pattern_theta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='start_item',
            field=models.PositiveIntegerField(default=1, help_text='Caso o índice seja 0, o primeiro item será escolhido de acordo com o critério de seleção de itens.', verbose_name='Item Inicial'),
        ),
    ]
