# Generated by Django 4.2.11 on 2026-02-11 02:25

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_alter_assessment_start_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tag de Questão',
                'verbose_name_plural': 'Tags de Questões',
                'db_table': 'question_tags',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='threshhold',
            field=models.CharField(default='0', help_text="Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional. O padrão '0' desabilita este critério de parada.", max_length=255, verbose_name='Critério de Parada CDM'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning.questiontag'),
        ),
    ]
