# Generated by Django 4.2.11 on 2026-02-13 01:16

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_questiontag_assessment_threshhold_question_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBalancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('weight', models.FloatField(default=1.0, verbose_name='Peso')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_balancers', to='learning.assessment')),
                ('question_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_balancers', to='learning.questiontag')),
            ],
            options={
                'verbose_name': 'Balanceador de Questões',
                'verbose_name_plural': 'Balanceadores de Questões',
                'db_table': 'question_balancers',
            },
        ),
    ]
