# Generated by Django 4.2.11 on 2026-02-13 01:45

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_questionbalancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='exposure_control',
            field=models.CharField(blank=True, choices=[('RE', 'Randomesque'), ('SH', 'Sympson-Hetter')], default=None, help_text='Método utilizado para controle de exposição de itens. Deixe em branco para desabilitar o controle de exposição.', max_length=255, null=True, verbose_name='Método de Controle de Exposição de Itens'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='exposure_values',
            field=models.CharField(default='0', help_text='Lista de valores, separados por vírgula, para controle de exposição de itens.', max_length=255, verbose_name='Valores de Controle de Exposição'),
        ),
        migrations.AlterField(
            model_name='questionbalancer',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Valor entre 0 e 1 que representa a importância relativa deste tag de questão na seleção de itens. A soma dos pesos para um mesmo assessment deve ser igual a 1.', verbose_name='Peso'),
        ),
        migrations.CreateModel(
            name='ShadowTestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('itens_query', models.CharField(default='', help_text='Query para seleção de itens para o teste sombra.', max_length=255, verbose_name='Query de Itens')),
                ('operator', models.CharField(choices=[('<=', 'Menor ou igual a'), ('>=', 'Maior ou igual a'), ('==', 'Igual a')], default='==', help_text='Operador utilizado para comparar a métrica do teste sombra com o valor de comparação.', max_length=2, verbose_name='Operador de Comparação')),
                ('value', models.FloatField(default=0.0, help_text='Valor utilizado para comparar a métrica do teste sombra, de acordo com o operador selecionado.', verbose_name='Valor de Comparação')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_test_config', to='learning.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
