# Generated by Django 4.2.11 on 2026-02-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_assessment_exposure_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shadowtestconfig',
            options={'verbose_name': 'Configuração de Teste Sombra', 'verbose_name_plural': 'Configurações de Teste Sombra'},
        ),
        migrations.AlterModelTable(
            name='shadowtestconfig',
            table='shadow_test_configs',
        ),
    ]
