# Generated by Django 4.2.11 on 2026-02-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_alter_shadowtestconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbalancer',
            options={'verbose_name': 'Balanceador de Conteúdo', 'verbose_name_plural': 'Balanceadores de Conteúdo'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='exposure_values',
            field=models.CharField(blank=True, default='0', help_text='Lista de valores, separados por vírgula, para controle de exposição de itens.', max_length=255, verbose_name='Valores de Controle de Exposição'),
        ),
        migrations.AlterField(
            model_name='shadowtestconfig',
            name='value',
            field=models.IntegerField(default=0, help_text='Valor utilizado para comparar a métrica do teste sombra, de acordo com o operador selecionado.', verbose_name='Valor de Comparação'),
        ),
    ]
