# Generated by Django 4.2.11 on 2026-02-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_alter_questionbalancer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionparams',
            name='irt_mparams',
        ),
        migrations.AddField(
            model_name='questionparams',
            name='mirt_difficulty',
            field=models.JSONField(default=list, verbose_name='Lista de Dificuldades'),
        ),
        migrations.AddField(
            model_name='questionparams',
            name='mirt_discrimination',
            field=models.JSONField(default=list, verbose_name='Lista de Discriminações'),
        ),
        migrations.AddField(
            model_name='questionparams',
            name='mirt_guess',
            field=models.JSONField(default=list, verbose_name='Lista de Chutes'),
        ),
        migrations.AddField(
            model_name='questionparams',
            name='mirt_upper_asymptote',
            field=models.JSONField(default=list, verbose_name='Lista de Assimptotas Superiores'),
        ),
    ]
