# Generated by Django 4.2.11 on 2026-02-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_alter_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='threshhold',
            new_name='threshold',
        ),
    ]
