# Generated by Django 4.2.11 on 2026-02-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_rename_threshhold_assessment_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionparams',
            name='mirt_difficulty',
        ),
        migrations.RemoveField(
            model_name='questionparams',
            name='mirt_guess',
        ),
        migrations.RemoveField(
            model_name='questionparams',
            name='mirt_upper_asymptote',
        ),
    ]
