# Generated by Django 4.2.11 on 2026-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_remove_questionparams_mirt_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='quadpts',
            field=models.PositiveIntegerField(default=21, help_text='Número de pontos de quadratura para integração numérica em modelos multidimensionais.', verbose_name='Pontos de Quadratura'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='theta_range',
            field=models.CharField(default='-4,4', help_text='Range de theta para integração numérica em modelos multidimensionais. Esse campo aceita dois valores separados por vírgula representando o limite inferior e superior do range.', max_length=255, verbose_name='Range de Theta'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='weights',
            field=models.JSONField(default=list, help_text='Lista de pesos, separados por vírgula, para critérios de seleção de itens multidimensionais.', verbose_name='Pesos para Critérios de Seleção de Itens Multidimensionais'),
        ),
    ]
