# Generated by Django 4.2.11 on 2026-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0033_assessment_quadpts_assessment_theta_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('4PL', 'TRI - 4PL'), ('3PL', 'TRI - 3PL'), ('2PL', 'TRI - 2PL'), ('1PL', 'TRI - 1PL (Rasch)'), ('M4PL', 'TRI - M4PL'), ('M3PL', 'TRI - M3PL'), ('M2PL', 'TRI - M2PL'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - G-DINA')], default='3PL', max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='questionparams',
            name='model',
            field=models.CharField(choices=[('4PL', 'TRI - 4PL'), ('3PL', 'TRI - 3PL'), ('2PL', 'TRI - 2PL'), ('1PL', 'TRI - 1PL (Rasch)'), ('M4PL', 'TRI - M4PL'), ('M3PL', 'TRI - M3PL'), ('M2PL', 'TRI - M2PL'), ('DINA', 'CDM - DINA'), ('DINO', 'CDM - DINO'), ('GDINA', 'CDM - G-DINA')], default='3PL', max_length=255, verbose_name='Modelo'),
        ),
    ]
