# Generated by Django 4.2.11 on 2026-03-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_alter_assessment_type_alter_questionparams_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='latent_covariances',
            field=models.JSONField(default=list, help_text="Lista de covariâncias latentes, separados por vírgula, para testes multidimensionais. O formato deve ser uma lista de valores separados por vírgula representando a matriz de covariância em formato linearizado (linha por linha). Por exemplo, para uma matriz 2x2: 'var1, cov12, var2'.", max_length=255, verbose_name='Covariâncias Latentes para Testes Multidimensionais'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='latent_means',
            field=models.JSONField(default=list, help_text='Lista de médias latentes, separados por vírgula, para testes multidimensionais.', max_length=255, verbose_name='Médias Latentes para Testes Multidimensionais'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='prior',
            field=models.JSONField(default=dict, help_text="Distribuição a priori para testes multidimensionais. O formato deve ser um dicionário com 2^k chaves. Ex.: {'000': 0.1, '001': 0.1, '010': 0.1, '011': 0.1, '100': 0.1, '101': 0.1, '110': 0.1, '111': 0.3} para um teste com 3 dimensões.", max_length=255, verbose_name='Distribuição a Priori para Testes Multidimensionais'),
        ),
    ]
