# Generated by Django 4.2.11 on 2026-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_assessment_latent_covariances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='kl_delta',
            field=models.FloatField(default=0.1, help_text='Valor de delta utilizado nos critérios de seleção baseados em divergência de Kullback-Leibler. Esse valor é subtraído do theta estimado para calcular a distribuição de probabilidade dos itens candidatos. O padrão é 0.1.', verbose_name='Delta para Critérios KL'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='latent_covariances',
            field=models.JSONField(default=list, help_text="Lista de covariâncias latentes, separados por vírgula. O formato deve ser uma lista de valores separados por vírgula representando a matriz de covariância em formato linearizado (linha por linha). Por exemplo, para uma matriz 2x2: 'var1, cov12, var2'.", max_length=255, verbose_name='Covariâncias Latentes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='latent_means',
            field=models.JSONField(default=list, help_text='Lista de médias latentes, separados por vírgula.', max_length=255, verbose_name='Médias Latentes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='prior',
            field=models.JSONField(default=dict, help_text="Distribuição a priori. O formato deve ser um dicionário com 2^k chaves. Ex.: {'000': 0.1, '001': 0.1, '010': 0.1, '011': 0.1, '100': 0.1, '101': 0.1, '110': 0.1, '111': 0.3} para um teste com 3 dimensões.", max_length=255, verbose_name='Distribuição a Priori'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='quadpts',
            field=models.PositiveIntegerField(default=21, help_text='Número de pontos de quadratura para integração numérica.', verbose_name='Pontos de Quadratura'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='theta_range',
            field=models.CharField(default='-4,4', help_text='Range de theta para integração numérica. Esse campo aceita dois valores separados por vírgula representando o limite inferior e superior do range.', max_length=255, verbose_name='Range de Theta'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='weights',
            field=models.JSONField(default=list, help_text='Lista de pesos, separados por vírgula, para critérios de seleção de itens.', verbose_name='Pesos para Critérios de Seleção de Itens'),
        ),
    ]
