# Generated by Django 4.2.11 on 2026-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_assessment_kl_delta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='latent_covariances',
            field=models.JSONField(blank=True, default=list, help_text="Lista de covariâncias latentes, separados por vírgula. O formato deve ser uma lista de valores separados por vírgula representando a matriz de covariância em formato linearizado (linha por linha). Por exemplo, para uma matriz 2x2: 'var1, cov12, var2'.", max_length=255, verbose_name='Covariâncias Latentes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='latent_means',
            field=models.JSONField(blank=True, default=list, help_text='Lista de médias latentes, separados por vírgula.', max_length=255, verbose_name='Médias Latentes'),
        ),
    ]
