# Generated by Django 4.2.11 on 2026-06-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_alter_assessment_latent_covariances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='weights',
            field=models.JSONField(blank=True, default=list, help_text='Lista de pesos, separados por vírgula, para critérios de seleção de itens.', verbose_name='Pesos para Critérios de Seleção de Itens'),
        ),
    ]
