# Generated by Django 4.2.11 on 2026-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userpool_userpoolhasuser_userpoolhasassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoolhasuser',
            name='thetas_start',
            field=models.CharField(default='0', help_text='Valor inicial de thetas desse Aluno para as Avaliações dessa turma. Esse campo aceita um único valor ou uma lista de valores separados por vírgula (,) em caso de teste multidimensional.', max_length=255, verbose_name='Thetas Iniciais'),
        ),
    ]
